In [1]:
import numpy as np
import pandas as pd

In [2]:
# q1

In [6]:
array1=np.array([[10,40,2],[100,18,785]])
array2=np.array([[19,200,998],[7,97,746]])
print("\ncomparison-greater")
print(np.greater(array1,array2))
print("\ncomparison-greater equal")
print(np.greater_equal(array1,array2))
print("\ncomparison -less")
print(np.less(array1,array2))


comparison-greater
[[False False False]
 [ True False  True]]

comparison-greater equal
[[False False False]
 [ True False  True]]

comparison -less
[[ True  True  True]
 [False  True False]]


In [7]:
#Q2



In [13]:
array0=np.zeros((5,2))
array1=np.ones((5,2))
array5=np.full((10),5)
print(array0)
print(array1)
print(array5)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[5 5 5 5 5 5 5 5 5 5]


In [14]:
#q4

In [15]:
array1=np.array([[10,40,2],[100,18,785]])
array2=np.array([[19,200,998],[7,97,746]])
print("Addition  ")
print(np.add(array1,array2))
print ("\n Substraction  ")
print(np.subtract(array1,array2))
print("\n Multiplication")
print(np.multiply(array1,array2))
print("\n Division ")
print(np.divide(array1,array2))


Addition  
[[  29  240 1000]
 [ 107  115 1531]]

 Substraction  
[[  -9 -160 -996]
 [  93  -79   39]]

 Multiplication
[[   190   8000   1996]
 [   700   1746 585610]]

 Division 
[[5.26315789e-01 2.00000000e-01 2.00400802e-03]
 [1.42857143e+01 1.85567010e-01 1.05227882e+00]]


In [4]:
#q5


In [5]:
array10 = np.array([[90,60,45],[30,180,360]])

print('sin(array):')
print('\n',np.sin(array10))

print('\ncos(array):')
print('\n',np.cos(array10))


print('\ntan(array):')
print('\n',np.tan(array10))

sin(array):

 [[ 0.89399666 -0.30481062  0.85090352]
 [-0.98803162 -0.80115264  0.95891572]]

cos(array):

 [[-0.44807362 -0.95241298  0.52532199]
 [ 0.15425145 -0.59846007 -0.28369109]]

tan(array):

 [[-1.99520041  0.32004039  1.61977519]
 [-6.4053312   1.33869021 -3.38014041]]


In [8]:
#q6

In [9]:
exam_data  = {'name': ['Ajith', 'Rakesh', 'Riya', 'Venkit', 'Niraj', 'Anupama', 'Akash', 'Chandra', 'Ram', 'Harish'],
        'score': [80, 25, 79, np.nan, 18, 23, 90, np.nan, 10, 78],
        'attempts': [1, 3, 2, 4, 2, 3, 2, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']


df = pd.DataFrame(exam_data , labels)
display(df)

name  score  attempts qualify
1     Ajith   80.0         1     yes
2    Rakesh   25.0         3      no
3      Riya   79.0         2     yes
4    Venkit    NaN         4      no
5     Niraj   18.0         2      no
6   Anupama   23.0         3     yes
7     Akash   90.0         2     yes
8   Chandra    NaN         1      no
9       Ram   10.0         2      no
10   Harish   78.0         1     yes

In [10]:
#Q7


In [16]:
#print specific coloumn
display(df[['name','score']])

name  score
1     Ajith   80.0
2    Rakesh   25.0
3      Riya   79.0
4    Venkit    NaN
5     Niraj   18.0
6   Anupama   23.0
7     Akash   90.0
8   Chandra    NaN
9       Ram   10.0
10   Harish   78.0

In [21]:
#q8

import pandas as pd

In [24]:
studentdata1 = pd.DataFrame({
        'student_id': ['A1', 'A2', 'A3', 'A4'],
         'name': ['Abhijith', 'Akash', 'Riya', 'Jose'], 
        'marks': [50, 75, 65,98]})

studentdata2 = pd.DataFrame({
        'student_id': ['A4', 'A5', 'A6', 'A7'],
        'name': ['Vikram', 'Venkit', 'Varsha', 'vidhu'], 
        'marks': [55, 58, 99,84]})

print("Original DataFrames:")
display(studentdata1)

print('******************')

display(studentdata2)

print("\nJoin the said two dataframes along rows:")
resultdata=pd.concat([studentdata1,studentdata2])
display(resultdata)


Original DataFrames:


student_id      name  marks
0         A1  Abhijith     50
1         A2     Akash     75
2         A3      Riya     65
3         A4      Jose     98

******************


student_id    name  marks
0         A4  Vikram     55
1         A5  Venkit     58
2         A6  Varsha     99
3         A7   vidhu     84


Join the said two dataframes along rows:


student_id      name  marks
0         A1  Abhijith     50
1         A2     Akash     75
2         A3      Riya     65
3         A4      Jose     98
0         A4    Vikram     55
1         A5    Venkit     58
2         A6    Varsha     99
3         A7     vidhu     84

In [25]:
#q9


In [28]:
print(df['score'].isnull())

1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
Name: score, dtype: bool


In [29]:
#Q10

In [31]:
dk=pd.Series([100,19,20.12,98,78.98])
print(dk)

0    100.00
1     19.00
2     20.12
3     98.00
4     78.98
dtype: float64
